name: Build and push image📦

on:
  workflow_dispatch:
  # schedule:
  #  - cron: "00 17 * * SAT"
  push:
    branches: ["http3"]
  # pull_request:
  #  branches: ["http3"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    if: github.actor == 'ammnt'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build the Docker image
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          provenance: false
          context: .
          platforms: linux/amd64
          load: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ammnt/nginx:http3
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Slim the Docker image
        uses: kitabisa/docker-slim-action@v1.0.3
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ammnt/nginx:http3
          tag: ammnt/nginx:http3
          overwrite: true

      - name: Slim the Docker image for GHCR
        uses: kitabisa/docker-slim-action@v1.0.3
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ghcr.io/ammnt/nginx:http3
          tag: ghcr.io/ammnt/nginx:http3
          overwrite: true

      - name: Push the Docker images
        run: |
          docker image push ammnt/nginx:http3
          docker image push ghcr.io/ammnt/nginx:http3
